platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!
target 'LotteryCharts' do 
pod 'AFNetworking'
pod 'ReactiveObjC'
pod 'SDWebImage'
pod 'Masonry'
pod 'YYModel'
pod 'FDFullscreenPopGesture'
pod 'MJRefresh'
pod 'TPKeyboardAvoiding'
pod 'RSKImageCropper'
pod 'Qiniu'
pod 'PYPhotoBrowser'
pod 'UMengUShare/Social/ReducedWeChat'
pod 'UMengUShare/Social/ReducedQQ'
end
