platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!
target 'PPSSBusiness' do 
pod 'AFNetworking'
pod 'ReactiveObjC'
pod 'SDWebImage'
pod 'Masonry'
pod 'YYModel'
pod 'FDFullscreenPopGesture'
pod 'MJRefresh'
pod 'TPKeyboardAvoiding'
pod 'SGQRCode'
pod 'RSKImageCropper'
end
